# Generated by Django 3.1.1 on 2020-10-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200930_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'github'), ('kakao', 'kakao')], default='email', max_length=50),
        ),
    ]
