# Generated by Django 3.1.2 on 2020-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20200930_2149'),
        ('lists', '0004_auto_20201110_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='list', to='rooms.Room'),
        ),
    ]
